In [1]:
from PIL import Image
import glob
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.linear_model import LogisticRegression

In [9]:
labels = pd.read_csv("Xray_TeethLabels_Simple.csv",index_col=0)
Ylabels = labels[5:]

metaY = labels[:3]

X = {}
Y = {}
count1 = 0
count2 = 0
count3 = 0
for picFilename in glob.glob("Processing2/processed/*"):
    patNumber =  picFilename.split('/')[2].split('_')[0]
    toothNumber = picFilename.split('/')[2].split('_')[1].split('.')[0]
    im = Image.open(picFilename)

    if int(metaY.loc['Age',patNumber]) < 25:
        count1+=1
        if 'Age1' in X.keys():
            X['Age1'][patNumber + '_' + toothNumber] = np.array(im).flatten()
            Y['Age1'].append(1 if Ylabels.loc[toothNumber,patNumber] == 'Yes' else 0)
        else:
            X['Age1'] = pd.DataFrame()
            X['Age1'][patNumber + '_' + toothNumber] = np.array(im).flatten()
            Y['Age1'] = [1 if Ylabels.loc[toothNumber,patNumber] == 'Yes' else 0]
    
    elif int(metaY.loc['Age',patNumber]) < 40:
        count2+=1
        if 'Age2' in X.keys():
            X['Age2'][patNumber + '_' + toothNumber] = np.array(im).flatten()
            Y['Age2'].append(1 if Ylabels.loc[toothNumber,patNumber] == 'Yes' else 0)
        else:
            X['Age2'] = pd.DataFrame()
            X['Age2'][patNumber + '_' + toothNumber] = np.array(im).flatten()
            Y['Age2'] = [1 if Ylabels.loc[toothNumber,patNumber] == 'Yes' else 0]
    
    else:
        count3+=1
        if 'Age3' in X.keys():
            X['Age3'][patNumber + '_' + toothNumber] = np.array(im).flatten()
            Y['Age3'].append(1 if Ylabels.loc[toothNumber,patNumber] == 'Yes' else 0)
        else:
            X['Age3'] = pd.DataFrame()
            X['Age3'][patNumber + '_' + toothNumber] = np.array(im).flatten()
            Y['Age3'] = [1 if Ylabels.loc[toothNumber,patNumber] == 'Yes' else 0]

In [15]:
print(count1)
print(count2)
print(count3)

80
60
84
dict_keys(['Age2', 'Age1', 'Age3'])


In [16]:
for age in X.keys():
    ageX = X[age]
    ageY = Y[age]

    X_train, X_test, y_train, y_test = train_test_split(ageX.T.to_numpy(), np.array(ageY), test_size=0.20)

    print(f"SVM modle for age: {age}")
    model = SVC(C=10, kernel='rbf')
    model.fit(X_train, y_train)
    print(model)
    # make predictions
    expected = y_test
    predicted = model.predict(X_test)
    # summarize the fit of the model
    print(metrics.classification_report(expected, predicted))
    print(metrics.confusion_matrix(expected, predicted))

    # print("KNN Accuracy: {}%".format(stat.mean(neighAcc)*100))

SVM modle for age: Age2
SVC(C=10)
              precision    recall  f1-score   support

           0       0.11      0.50      0.18         2
           1       0.67      0.20      0.31        10

    accuracy                           0.25        12
   macro avg       0.39      0.35      0.24        12
weighted avg       0.57      0.25      0.29        12

[[1 1]
 [8 2]]
SVM modle for age: Age1
SVC(C=10)
              precision    recall  f1-score   support

           0       0.67      0.67      0.67         9
           1       0.57      0.57      0.57         7

    accuracy                           0.62        16
   macro avg       0.62      0.62      0.62        16
weighted avg       0.62      0.62      0.62        16

[[6 3]
 [3 4]]
SVM modle for age: Age3
SVC(C=10)
              precision    recall  f1-score   support

           0       0.92      0.80      0.86        15
           1       0.25      0.50      0.33         2

    accuracy                           0.76       

In [17]:
for age in X.keys():
    ageX = X[age]
    ageY = Y[age]

    X_train, X_test, y_train, y_test = train_test_split(ageX.T.to_numpy(), np.array(ageY), test_size=0.20)

    print(f"SVM modle for age: {age}")
    model = SVC(C=10, kernel='linear')
    model.fit(X_train, y_train)
    print(model)
    # make predictions
    expected = y_test
    predicted = model.predict(X_test)
    # summarize the fit of the model
    print(metrics.classification_report(expected, predicted))
    print(metrics.confusion_matrix(expected, predicted))

    # print("KNN Accuracy: {}%".format(stat.mean(neighAcc)*100))

SVM modle for age: Age2
SVC(C=10, kernel='linear')
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         6
           1       0.00      0.00      0.00         6

    accuracy                           0.50        12
   macro avg       0.25      0.50      0.33        12
weighted avg       0.25      0.50      0.33        12

[[6 0]
 [6 0]]
SVM modle for age: Age1


/usr/local/anaconda3/envs/opencv/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/anaconda3/envs/opencv/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/anaconda3/envs/opencv/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVC(C=10, kernel='linear')
              precision    recall  f1-score   support

           0       0.56      1.00      0.71         5
           1       1.00      0.64      0.78        11

    accuracy                           0.75        16
   macro avg       0.78      0.82      0.75        16
weighted avg       0.86      0.75      0.76        16

[[5 0]
 [4 7]]
SVM modle for age: Age3
SVC(C=10, kernel='linear')
              precision    recall  f1-score   support

           0       0.85      0.85      0.85        13
           1       0.50      0.50      0.50         4

    accuracy                           0.76        17
   macro avg       0.67      0.67      0.67        17
weighted avg       0.76      0.76      0.76        17

[[11  2]
 [ 2  2]]
